### ISSUE TITLE
Typo on documentation page

### ISSUE THREAD

**Issue by daniel-de-wit** [isleofcode/ember-cordova-splash#2]
The example shown on this page: http://embercordova.com/pages/addons/splash
has a typo:

```
export default Route.extend({
  splashscreenService: service('ember-cordova/splash'),

  afterModel() {
    this.get('splashScreenService').hide();
  }
  // ...
});
```

Notice `splashscreenService` vs `get('splashScreenService')`

**Comment by alexblom** [comment]
Thanks for reporting - has since been resolved.
